### PR TITLE
Fix many typos

### PR DESCRIPTION
**Pull request by quentinus95**
This also includes a bugfix for the `$head` variable causing my app to crash.

### CODE REVIEW

**Comment by quentinus95** [comment]
It would be awsome if we could use `php-cs-fixer` on this repo, it would avoid many code smells. I can open a PR with travis integration and files rewriting if you want.

**Comment by Sebi94nbg** [comment]
@quentinus95 This would be very awesome, when you could create a PR with the `php-cs-fixer` integration. I didn't knew this software, but it looks very useful.

My target is to update this library to PSR4 standard, so we maybe can already configure this standard? I also want to improve the maintainability as it's currently only a `D`: https://codeclimate.com/github/barbushin/php-imap

**Comment by quentinus95** [comment]
@Sebi94nbg sure.

In the meantime, can you release a new path version of the lib?

Thx

**Comment by Sebi94nbg** [comment]
I was right about to do this. :D

Done: [3.021](https://github.com/barbushin/php-imap/releases/tag/3.0.21)

**Comment by quentinus95** [comment]
Awesome, thanks!

**Comment by Sebi94nbg** [comment]
Any progress on the `php-cs-fixer` integration, @quentinus95 ? :)

**Comment by quentinus95** [comment]
I've got an awesomly busy week, but it's definetly on my todolist 😃

**Pull request merged**
