### PR TITLE
Chore/update php cs fixer

### PR DESCRIPTION
**Pull request by aragon999**
This pull request currently includes #595 (since this does some prior work) and #598 (which I needed since I am running php8) if these two pull requests are merged I am happy to rebase this PR.

### CODE REVIEW

**Comment by Sebi94nbg** [comment]
Both referenced pull requests have been merged. This requires a rebase now.

**Comment by aragon999** [comment]
I rebased, but I am quite confused why the merge commit is still shown in this PR.

Locally everything seems fine, as far as I can tell:
grafik

**Comment by Sebi94nbg** [comment]
The `develop` branch for now please. :)

The mentioned commits / pull requests were only merged to develop.

I'm already thinking about removing this develop branch as it doesn't really make sense in this project. We could also simply branch from the default branch.

But for now: Develop. :)

**Comment by aragon999** [comment]
Thanks for the feedback.

Yeah I mean the branches really depend on the desired workflow. Personally I actually like to work with a `master`/`trunk` branch and only have feature branches (and version branches, if one wants to offer bugfix releases).

**Comment by Sebi94nbg** [comment]
Approved - checks are running. One already failed. 🙈

Yeah, there are a lot of different approaches to how to work with branches and every company or whatever is handling it more or less different. :D

**Comment by aragon999** [comment]
Yes, sorry I forgot some changes, and did not check properly what has changed in the `develop` branch. 

I added some changes, but unfortunately locally the psalm command still fails:
```
  Error on line 12:
    Element '{https://getpsalm.org/schema/config}psalm', attribute 'requireVoidReturnType': The attribute 'requireVoidReturnType' is not allowed.
```

Although I updated psalm to the version which should include this option. Not sure, hope the pipelines do not fail anymore.

**Comment by aragon999** [comment]
I just checked, for me psalm also fails locally without my changes.

I can also not find the attribute in the XML schema: https://psalm.dev/schema/config

**Comment by Sebi94nbg** [comment]
Let's fix these issues in a different merge request.

**Pull request merged**
