### PR TITLE
Extended getMailHeader()

### PR DESCRIPTION
**Pull request by Sebi94nbg**
Added support for getting the headers "Precedence" and "Auto-Submitted".

Excerpt from the [RFC2076](http://www.faqs.org/rfcs/rfc2076.html):
> *Precedence: Non-standard, controversial, discouraged.*
> Sometimes used as a priority value which can influence transmission speed and delivery. Common values are "bulk" and "first-class". Other uses is to control automatic replies and to control return-of-content facilities, and to stop mailing list loops.

Excerpt from the [RFC3834](https://tools.ietf.org/html/rfc3834):
> *Auto-Submitted field*
> The Auto-Submitted field, with a value of "auto-replied", SHOULD be included in the message header of any automatic response.

I've added this support to be able to parse emails better. Depending on these headers, you can decide, if you send an automatic reply back or not or if you even do anything with this email or not.

### CODE REVIEW

**Comment by Sebi94nbg** [comment]
#290

**Comment by Sebi94nbg** [comment]
Relates to #176.

**Comment by barbushin** [comment]
@Sebi94nbg Please check merge conflicts

**Comment by Sebi94nbg** [comment]
@barbushin done!

**Comment by barbushin** [comment]
@Sebi94nbg Released :)

**Comment by Sebi94nbg** [comment]
@barbushin can you please check, why https://packagist.org/packages/php-imap/php-imap is still showing the previous version?

**Pull request merged**
