### PR TITLE
Composer.json: Add support for PHP 8

### PR DESCRIPTION
**Pull request by janbarasek**
Hi, I want to upgrade my application to PHP 8. :)

This package is compatible with PHP 7.4, so I think version 8 should be compatible too.

Thanks.

### CODE REVIEW

**Comment by michaljusiega** [comment]
But remember - PHP 8.1 will be not compatible - see https://php.watch/versions/8.1#IMAPConnection-resource

**Comment by janbarasek** [comment]
@michaljusiega Oh, I see. I updated the dependency from PHP 8.0 to <8.1.

**Comment by michaljusiega** [comment]
Related issue: https://github.com/barbushin/php-imap/issues/563

Friendly ping: @barbushin @bapcltd-marv @Sebi94nbg

**Comment by voicecode-bv** [comment]
Hello! Can you please give an update about when this will be released?

**Comment by gabrielkoerich** [comment]
Will this be tagged?

**Pull request merged**
