### PR TITLE
Adding support for "original" Filename.

### PR DESCRIPTION
**Pull request by fglueck**
$mailbox->setAttachmentsFilenameMode(Mailbox::ATTACH_FILE_NAMERANDOM); # filename by random (old way)
$mailbox->setAttachmentsFilenameMode(Mailbox::ATTACH_FILE_NAMEORIGINAL); # filename by email

### CODE REVIEW

**Comment by fglueck** [comment]
$mailbox->setAttachmentsFilenameMode(Mailbox::ATTACH_FILE_NAMEORIGINAL);

**Comment by bapcltd-marv** [comment]
this'll fall over the moment someone sends an email with duplicate filenames in.

**Comment by Sebi94nbg** [comment]
Yes, that's true, but this shouldn't be our problem.

Implementing this is a valid reason as you could for example fetch new (unread) emails, save their attachments with the original file name (as this is required for further processing by eg. a (custom) software) and process them regulary/immediately (eg. regular data import).

The developer, who is implementing this using the original file name needs to ensure, that this will never fail due to duplicate file names. The default behaviour will be still random file names, so... Yeah. If someone decides to use the original file names, this person should know, which side affects this could have.

**Comment by bapcltd-marv** [comment]
making it easier for end users without it being the default is good :D

**Comment by Sebi94nbg** [comment]
Has been already implemented. See #633.

**Comment by fglueck** [comment]
I this a joke? This patch was created in may. Yours (#633) just 4 days ago.
And your true/false implementation has no flexibitlity to adding other modes, like OVERWRITE/POSTFIXING ...

**Comment by Sebi94nbg** [comment]
Sorry, but when there is no feedback for over 6 months, what do you expect will happen here?

Yes, that's true. The boolean implementation does not allow further modes, but as I asked in this merge request some time ago: Do you expect any other modes? I thought about it and I didn't see any other modes than the current implementation (random filenames) or the original filename implementation. That's the reason, why I sticked to a boolean solution.

These changes are not merged into the default branch yet, so feel free to create a new merge request with your recommended changes. If you have any further possible modes, feel free to add them also, so that there are not only two different modes.

I'm currently planing to merge and release a new version by latest end of this week.

**Comment by fglueck** [comment]
I think it is possible to implement a mode "replace" and "version". So if files are "double" you can select "replace" or generte a filename like Dokument(x).pdf. (x) inkrement by each export.

**Comment by Sebi94nbg** [comment]
Yes, this sounds useful. Awesome idea!

Do you create a pull request with those changes and these two modes or should I?

**Comment by fglueck** [comment]
I do the pull request, other features cames in the next month.

**Pull request closed without merging**
