### PR TITLE
 Fix an issue that checking valid params in the setConnectionArgs function.

### PR DESCRIPTION
**Pull request by ddcatgg**
array_key_exists() -> in_array()

### CODE REVIEW

**Comment by Sebi94nbg** [comment]
When do you face this issue with `array_key_exists()`? Do you have an example?

The PHPUnit tests do not face any issue with this.

**Comment by ddcatgg** [comment]
> When do you face this issue with `array_key_exists()`? Do you have an example?
> 
> The PHPUnit tests do not face any issue with this.

The following code:

    $mailbox->setConnectionArgs(0, 0, ['DISABLE_AUTHENTICATOR' => 'GSSAPI']);

will raise:

    Exception 'PhpImap\Exceptions\InvalidParameterException' with message 'Invalid array key of params provided for setConnectionArgs()! Only DISABLE_AUTHENTICATOR is currently valid.'


Because `$supported_params` is initialized to an numerically indexed array, `array_key_exists` cannot be used to detect items in it.

    $supported_params = array('DISABLE_AUTHENTICATOR');

**Comment by Sebi94nbg** [comment]
That's interesting. This means, that the PHPUnit tests are not working as expected: https://github.com/barbushin/php-imap/blob/master/tests/unit/MailboxTest.php#L566-L594

**Comment by Sebi94nbg** [comment]
Tested it - I can confirm this.

**Comment by Sebi94nbg** [comment]
Figured the issue with PHPUnit out. I'll fix these issues.

**Pull request merged**
