### PR TITLE
Removed PHP 5.x and 7.0

### PR DESCRIPTION
**Pull request by Sebi94nbg**
PHP 5.x and 7.0 is outdated and not supported anymore, so we should focus on current supported versions.

There are also some dependencies due to PHPUnit, which require at least PHP 7.1.x.

### CODE REVIEW

**Comment by barbushin** [comment]
PHP 7.0 is used by 20% of projects https://kinsta.com/blog/php-versions/

So maybe for current milestone  we can use `"phpunit/phpunit": "~5.7.27"` that works on PHP >= 5.6?

**Comment by barbushin** [comment]
@Sebi94nbg fyi, phpunit >= 6.0 works only on php >= 7.0

**Comment by Sebi94nbg** [comment]
Sure, we can also do this. Let me quickly update it.

**Comment by Sebi94nbg** [comment]
@barbushin this is a bit tricky as each PHPUnit version until 8.x works only on one specific version:

- PHPUnit 5.x => PHP 5.6
- PHPUnit 6.x => PHP 7.0
- PHPUnit 7.x => PHP 7.1
- PHPUnit 8.x => PHP 7.2 or 7.3

With PHP `>=5.6` and PHPUnit `~5.7.27`, the build is failing for PHP 5.6 and 7.0: https://travis-ci.org/barbushin/php-imap/builds/526130872

**Comment by Sebi94nbg** [comment]
Great - it's working fine now with PHP 5.6 until 7.3. :)

Thx for fixing the composer file(s), @barbushin!

**Comment by barbushin** [comment]
@Sebi94nbg Thanks man for your contribution!

**Pull request merged**
