### PR TITLE
make expunge on disconnect optional

### PR DESCRIPTION
**Pull request by 1allen**
subj

### CODE REVIEW

**Comment by kikimor** [comment]
:+1:

**Comment by DD174** [comment]
:+1:

**Comment by miramir** [comment]
:+1:

**Comment by barbushin** [comment]
:+1: but... could you please move it to separate method? It's not a good idea to store all configuration options in constructor. I think it's already too much.

Thank you!

**Comment by 1allen** [comment]
something like that? :)

**Comment by barbushin** [comment]
:+1:

**Comment by barbushin** [comment]
somebody please confirm that it works, so I'll publish release for Composer

**Comment by barbushin** [comment]
released

**Comment by 1allen** [comment]
:+1:

**Pull request merged**
