### PR TITLE
Added Header Data

### PR DESCRIPTION
**Pull request by hexathos**
According to https://github.com/barbushin/php-imap/issues/102 added header data, and raw data of them to IncomingMail.

Signed-off-by: Rainer Bendig <hexathos@gmail.com>

### CODE REVIEW

**Comment by Resource-xx** [comment]
I think adding methods like:
`boolean IncomingMail::hasHeader($headerName) `
and 
`string IncomingMail::getHeader($headerName)`
would be useful too.

**Comment by quentinus95** [comment]
:+1: Please merge this pull request and add it to a new release, I need this feature.

**Comment by quentinus95** [comment]
@barbushin

**Comment by barbushin** [comment]
Released

**Comment by quentinus95** [comment]
Thanks a lot !

**Pull request merged**
