### PR TITLE
Removed redundancy

### PR DESCRIPTION
**Pull request by vhinmanansala**
Removed functions that are doing the same thing

### CODE REVIEW

**Comment by barbushin** [comment]
Sorry, I can't merge this PR. We should keep backward compatibility.

**Comment by vhinmanansala** [comment]
Can you enlighten me with the backward compatibility part?

**Comment by barbushin** [comment]
There is a big chance that somebody is already using this methods, so if we remove it, they'll get fatal error after updating library.

**Comment by vhinmanansala** [comment]
Sorry, this might be a pretty dumb question. But, is there a workaround with this issue?

**Comment by barbushin** [comment]
Yes. If there will be major release of php-imap, for example `3.0`, then we can remove this methods. But for now I just don't think that this is reasonable.

**Comment by vhinmanansala** [comment]
Thank you.

**Pull request closed without merging**
