### PR TITLE
fixes for #496 & #514

### PR DESCRIPTION
**Pull request by bapcltd-marv**
draft pending acceptance by issue reporter

### CODE REVIEW

**Comment by liushuo1** [comment]
I also encountered this picture problem. When can this be used?

**Comment by bapcltd-marv** [comment]
If you're comfortable with manually patching files, the pertinent changes are:
* a928614 corrects the `preg_match_all` usage
* c5debb6 & d2d8d96 bypass the internal access to `IncomingMail::$textHtml` (which can result in a blank email if not accessed prior to these methods being called)

**Comment by liushuo1** [comment]
Hi, bother you again, this is the complete case on https://github.com/barbushin/php-imap/wiki/Getting-Started, the calling picture is still cid, how can I do it?

**Comment by bapcltd-marv** [comment]
[IncomingMail::embedImageAttachments()](https://github.com/barbushin/php-imap/blob/b5e4cda2ffa4a04bec0789ee5f8019d7f839ced0/src/PhpImap/IncomingMail.php#L201) or [IncomingMail::replaceInternalLinks()](https://github.com/barbushin/php-imap/blob/b5e4cda2ffa4a04bec0789ee5f8019d7f839ced0/src/PhpImap/IncomingMail.php#L175)

**Comment by liushuo1** [comment]
Thank you very much for your answers, the cid image has been resolved.

**Comment by wehaveaplan** [comment]
After patching I still faced the same issue. 

I noticed that $attachment->disposition in the function embedImageAttachments returned INLINE in caps, causing 'inline' == $attachment->disposition to return false. Hosting depended maybe?

I changed this to 'inline' == strtolower($attachment->disposition) and it's working now.

**Comment by bapcltd-marv** [comment]
> I changed this to 'inline' == strtolower($attachment->disposition) and it's working now.

@wehaveaplan is that on the package code or in your own code ?

**Comment by wehaveaplan** [comment]
@bapcltd-marv 
On the package in the file IncomingMail.php in the function embedImageAttachments just after the foreach statement.

**Comment by bapcltd-marv** [comment]
> @bapcltd-marv
> On the package in the file IncomingMail.php in the function embedImageAttachments just after the foreach statement.

Could you please file a new issue and I'll have a look at that in the morning ?

**Pull request merged**
