### PR TITLE
Modify/decoding method

### PR DESCRIPTION
**Pull request by lancoLiu**

### CODE REVIEW

**Comment by Sebi94nbg** [comment]
Thanks for your PR, @lancoLiu!

What is the reason for this change? Your change would undo a hotfix from the past, which was required to fix an issue.

**Comment by lancoLiu** [comment]
When my email contains a large attachment, the attachment exceeds the memory_limit setting and an error occurs. I have tested that the imap_base64 function can be replaced by the base64_decode function, which works fine without the need for preg_replace

**Comment by lancoLiu** [comment]
> Thanks for your PR, @lancoLiu!
> 
> What is the reason for this change? Your change would undo a hotfix from the past, which was required to fix an issue.

When my email contains a large attachment, the attachment exceeds the memory_limit setting and an error occurs. I have tested that the imap_base64 function can be replaced by the base64_decode function, which works fine without the need for preg_replace

If the data exceeds the setting value of memory_limit, the preg_replace function will fail. I think base64_decode ($this-> data, false) can replace the original operation.

**Comment by bapcltd-marv** [comment]
> Your change would undo a hotfix from the past

am I reading the regex correctly that it's intended to remove non-base64 characters from the data?

**Comment by lancoLiu** [comment]
> > Your change would undo a hotfix from the past
> 
> am I reading the regex correctly that it's intended to remove non-base64 characters from the data?

I think so, I think base64_decode ($this-> data, false) can do this

**Comment by bapcltd-marv** [comment]
> > > Your change would undo a hotfix from the past
> > 
> > 
> > am I reading the regex correctly that it's intended to remove non-base64 characters from the data?
> 
> I think so, I think base64_decode ($this-> data, false) can do this

@Sebi94nbg can you patch in a test file that required the hotfix ?

**Comment by Sebi94nbg** [comment]
Mhmm, ok. Then let's change that piece of code to `base64_decode()` only and see, what the automated tests say.

**Comment by bapcltd-marv** [comment]
> Mhmm, ok. Then let's change that piece of code to `base64_decode()` only and see, what the automated tests say.

I was thinking more along the lines of having a new test method with a data provider that provides a pair of input strings & expected results, where the test compares both "`preg_replace()` paired with `imap_base64()`" and "`base64_decode($str, false)`" by itself.

i.e.

```php
/**
* @dataProvider Base64DecodeProvider
*
* @param string $input
* @param string $expected
*
* @return void
*/
public function testBase64Decode($input, $expected) {
    $this->assertSame($expected, /* the preg_replace code */);
    $this->assertSame($expected, /* the base64_decode code */);
}
```

then if we ever find a string that doesn't pass both, we can update the data provider, update the test, and change the `DataPartInfo` code again.

**Comment by Sebi94nbg** [comment]
Ah, ok. Yes, we can do it that way as well. :D

This weekend I should finally find some time to check all the issues and PR here. Then I'll test everything and release a new version.

**Comment by Sebi94nbg** [comment]
@bapcltd-marv I've added some test cases. See above commit(s).

Currently, the build is only failing in one of two PHP 7.4 jobs: https://travis-ci.org/github/barbushin/php-imap/builds/676350984

**Comment by bapcltd-marv** [comment]
> ERROR: RedundantConditionGivenDocblockType - tests/unit/LiveMailboxTest.php:104:31 - Docblock type resource always contains resource (see https://psalm.dev/156)
            $this->assertTrue(\is_resource($mailbox->getImapStream()));

`MailBox::getImapStream()` "always" returns a resource, so the assertion is no longer necessary.

**Pull request closed without merging**
