### PR TITLE
Add method to fetch raw email message

### PR DESCRIPTION
**Pull request by tomhorvat**
Sometimes you want to use another mail parser and you need raw message.

```php
$rawMail = $mailbox->getRawMail($mailId);
```

### CODE REVIEW

**Comment by patie** [comment]
little OT is there parser from file/string (raw mail file from mail server) without need imap stream?

**Comment by tomhorvat** [comment]
I'm using this:

https://github.com/php-mime-mail-parser/php-mime-mail-parser

**Comment by barbushin** [comment]
Good idea, but... if you're going to use another mail parse, why do you need php-imap? :)

**Comment by tomhorvat** [comment]
Well, I was using before mentioned parser only because it has output for html with embedded images (it doesn't save them locally) and your class is perfect wrapper for handling imap operations :smile: 

https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/master/src/Parser.php#L223

Perhaps that would be a good addition to your class!

**Comment by barbushin** [comment]
BTW, php-imap also handles embedded images https://github.com/barbushin/php-imap/blob/master/src/PhpImap/IncomingMail.php#L48

**Comment by tomhorvat** [comment]
I know! I just needed solution to inline cid attachments but not use local filesystem...

**Pull request merged**
