### PR TITLE
Bugfix: Fix code of composer require from master branch in README

### PR DESCRIPTION
**Pull request by arkadiusjonczek**

### CODE REVIEW

**Comment by arkadiusjonczek** [comment]
pls review @barbushin :)

**Comment by barbushin** [comment]
We don't require from master branch in composer, only releases :)

**Comment by arkadiusjonczek** [comment]
I think you didn't understand this fix.

Your description is:
> Install the latest available and stable source code from `master`, which is may not released / tagged yet:

And your code line for this description is wrong:
`composer require php-imap/php-imap`

So I just fixed the code line of your description to be consistent:
`composer require php-imap/php-imap:dev-master`

By simply closing this PR without getting feedback it seems that you don't appreciate someone effort fixing your mistakes. 👎

**Comment by barbushin** [comment]
Oh sorry. I just didn't checked that README

**Comment by arkadiusjonczek** [comment]
Thank you 👍

**Pull request merged**
